[package]
name = "Ingestion"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.26.2"
bitcoincore-rpc = "0.17.0" 
tokio = { version = "1", features = ["full"] }
chrono = "0.4"
clap = { version = "4.5.18", features = ["derive"] }
